apiVersion: v1
kind: ConfigMap
metadata:
  name: music-man-config
  namespace: {{ .Values.namespace }}
  labels:
    app: music-man
data:
  # Log level configuration
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}

  # Database configuration
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: {{ .Values.database.env.database | quote }}
  DB_USER: {{ .Values.database.env.user | quote }}
